/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as HealthzRouteImport } from './routes/healthz'
import { Route as ApiEventsRouteImport } from './routes/api/events'
import { Route as ApiObserveRouteImport } from './routes/api/observe'
import { Route as ApiEventsIdRouteImport } from './routes/api/events.$id'
import { Route as ApiRoomsRoomSurvivalRateRouteImport } from './routes/api/rooms.$room.survival-rate'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const HealthzRoute = HealthzRouteImport.update({
  id: '/healthz',
  path: '/healthz',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiEventsRoute = ApiEventsRouteImport.update({
  id: '/api/events',
  path: '/api/events',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiObserveRoute = ApiObserveRouteImport.update({
  id: '/api/observe',
  path: '/api/observe',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiEventsIdRoute = ApiEventsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ApiEventsRoute,
} as any)
const ApiRoomsRoomSurvivalRateRoute =
  ApiRoomsRoomSurvivalRateRouteImport.update({
    id: '/api/rooms/$room/survival-rate',
    path: '/api/rooms/$room/survival-rate',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/healthz': typeof HealthzRoute
  '/api/events': typeof ApiEventsRouteWithChildren
  '/api/observe': typeof ApiObserveRoute
  '/api/events/$id': typeof ApiEventsIdRoute
  '/api/rooms/$room/survival-rate': typeof ApiRoomsRoomSurvivalRateRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/healthz': typeof HealthzRoute
  '/api/events': typeof ApiEventsRouteWithChildren
  '/api/observe': typeof ApiObserveRoute
  '/api/events/$id': typeof ApiEventsIdRoute
  '/api/rooms/$room/survival-rate': typeof ApiRoomsRoomSurvivalRateRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/healthz': typeof HealthzRoute
  '/api/events': typeof ApiEventsRouteWithChildren
  '/api/observe': typeof ApiObserveRoute
  '/api/events/$id': typeof ApiEventsIdRoute
  '/api/rooms/$room/survival-rate': typeof ApiRoomsRoomSurvivalRateRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/healthz'
    | '/api/events'
    | '/api/observe'
    | '/api/events/$id'
    | '/api/rooms/$room/survival-rate'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/healthz'
    | '/api/events'
    | '/api/observe'
    | '/api/events/$id'
    | '/api/rooms/$room/survival-rate'
  id:
    | '__root__'
    | '/'
    | '/healthz'
    | '/api/events'
    | '/api/observe'
    | '/api/events/$id'
    | '/api/rooms/$room/survival-rate'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  HealthzRoute: typeof HealthzRoute
  ApiEventsRoute: typeof ApiEventsRouteWithChildren
  ApiObserveRoute: typeof ApiObserveRoute
  ApiRoomsRoomSurvivalRateRoute: typeof ApiRoomsRoomSurvivalRateRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/healthz': {
      id: '/healthz'
      path: '/healthz'
      fullPath: '/healthz'
      preLoaderRoute: typeof HealthzRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/events': {
      id: '/api/events'
      path: '/api/events'
      fullPath: '/api/events'
      preLoaderRoute: typeof ApiEventsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/observe': {
      id: '/api/observe'
      path: '/api/observe'
      fullPath: '/api/observe'
      preLoaderRoute: typeof ApiObserveRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/events/$id': {
      id: '/api/events/$id'
      path: '/$id'
      fullPath: '/api/events/$id'
      preLoaderRoute: typeof ApiEventsIdRouteImport
      parentRoute: typeof ApiEventsRoute
    }
    '/api/rooms/$room/survival-rate': {
      id: '/api/rooms/$room/survival-rate'
      path: '/api/rooms/$room/survival-rate'
      fullPath: '/api/rooms/$room/survival-rate'
      preLoaderRoute: typeof ApiRoomsRoomSurvivalRateRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface ApiEventsRouteChildren {
  ApiEventsIdRoute: typeof ApiEventsIdRoute
}

const ApiEventsRouteChildren: ApiEventsRouteChildren = {
  ApiEventsIdRoute: ApiEventsIdRoute,
}

const ApiEventsRouteWithChildren = ApiEventsRoute._addFileChildren(
  ApiEventsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  HealthzRoute: HealthzRoute,
  ApiEventsRoute: ApiEventsRouteWithChildren,
  ApiObserveRoute: ApiObserveRoute,
  ApiRoomsRoomSurvivalRateRoute: ApiRoomsRoomSurvivalRateRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
